return {
	{ "nvim-lualine/lualine.nvim", enabled = false },
	{ "nvim-neo-tree/neo-tree.nvim", enabled = false },
	{ "folke/flash.nvim", enabled = false },
	{ "folke/lazydev.nvim", enabled = false },
	{ "echasnovski/mini.ai", enabled = false },
	{ "folke/noice.nvim", enabled = false },
	{ "mfussenegger/nvim-lint", enabled = false },
	{ "windwp/nvim-ts-autotag", enabled = false },
	{ "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
	{ "folke/persistence.nvim", enabled = false },
	{ "folke/todo-comments.nvim", enabled = false },
	{ "folke/ts-comments.nvim", enabled = false },
	--{ "folke/snacks.nvim", enabled = false },
	{ "folke/lazy.nvim", version = false },
	{ "LazyVim/LazyVim", version = false },
	{ "nvimdev/dashboard-nvim", enabled = false },
}
